version: '3'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

